import {seedModules,seedQuestions} from './data.js?v=10';
import {buildAdaptiveQuestionSet,calculateMastery,scheduleCard,updateStreak} from './quiz-engine.js?v=10';
import {collectStudyStatements,generatePdfQuestions,reconstructPageText,upgradeCustomModule} from './pdf-question-generator.js?v=10';

const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const storeKey='pulso-study-v4';
const defaults={attempts:[],mistakes:{},moduleStats:{},cardProgress:{},seenQuestions:[],completedModules:[],streak:0,customModules:[]};
let stored={};
try{const current=localStorage.getItem(storeKey);if(current)stored=JSON.parse(current);else stored=JSON.parse(localStorage.getItem('pulso-study-v3')||localStorage.getItem('pulso-study-v2')||localStorage.getItem('pulso-study-v1')||'{}')}catch{}
let state={...defaults,...stored,cardProgress:stored.cardProgress||{},seenQuestions:stored.seenQuestions||[],completedModules:stored.completedModules||[],customModules:(stored.customModules||[]).map(module=>module.generatorVersion===3?module:upgradeCustomModule(module))};
let session={module:'all',difficulty:'all',count:10,mode:'study',questions:[],index:0,score:0,streak:0,maxStreak:0,answers:[],answered:false};
let cardSession={cards:[],index:0,revealed:false};

const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
const modules=()=>[...seedModules,...state.customModules];
const questions=()=>[...seedQuestions,...state.customModules.flatMap(module=>module.questions||[])];
const shuffle=items=>[...items].sort(()=>Math.random()-.5);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const difficultyLabel=value=>({all:'Adaptativa',easy:'Fácil',medium:'Media',hard:'Difícil',exam:'Examen'}[value]||value);
const difficultySkill=value=>({easy:'Recuerdo guiado',medium:'Aplicación',hard:'Análisis multiconcepto',exam:'Casos y síntesis'}[value]||'Práctica adaptativa');

function show(name,title,eyebrow='Tu espacio de estudio'){
  $$('.view').forEach(view=>view.classList.toggle('active',view.id===name));
  $$('nav button').forEach(button=>{const active=button.dataset.go===name;button.classList.toggle('active',active);active?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current')});
  $('#pageTitle').textContent=title;$('#eyebrow').textContent=eyebrow;
  window.scrollTo({top:0,behavior:'smooth'});
}
function stats(){const total=state.attempts.reduce((sum,item)=>sum+item.total,0),correct=state.attempts.reduce((sum,item)=>sum+item.correct,0);return{attempts:state.attempts.length,total,accuracy:total?Math.round(correct/total*100):0}}
function moduleProgress(id){const item=state.moduleStats[id],pool=questions().filter(question=>question.module===id),seen=pool.filter(question=>state.seenQuestions.includes(question.id)).length;return calculateMastery({correct:item?.correct||0,total:item?.total||0,seen,target:Math.min(40,pool.length)})}
function isUnlocked(question){return state.seenQuestions.includes(question.id)||state.completedModules.includes(question.module)||Boolean(state.mistakes[question.id])}
function unlockedCards(){return questions().filter(isUnlocked)}
function dueCards(){const now=Date.now();return unlockedCards().filter(q=>!state.cardProgress[q.id]||state.cardProgress[q.id].due<=now).sort((a,b)=>(state.mistakes[b.id]||0)-(state.mistakes[a.id]||0))}
function learningScore(){const summary=stats(),knownIds=new Set(questions().map(question=>question.id)),seen=state.seenQuestions.filter(id=>knownIds.has(id)).length,target=Math.min(questions().length,modules().length*40),quiz=calculateMastery({correct:state.attempts.reduce((sum,item)=>sum+item.correct,0),total:summary.total,seen,target}),unlocked=unlockedCards(),mature=unlocked.filter(q=>(state.cardProgress[q.id]?.interval||0)>=3).length,cardScore=unlocked.length?mature/unlocked.length*100:0;return Math.round(quiz*.45+cardScore*.55)}
function updateChrome(){const mistakes=Object.keys(state.mistakes).length,due=dueCards().length;$('#mistakeBadge').textContent=mistakes;$('#mistakeBadge').hidden=mistakes===0;$('#dueBadge').textContent=due;$('#dueBadge').hidden=due===0;$('#headerStreak').textContent=state.streak}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),3200)}

function moduleCard(module,mode='quiz'){
  const total=questions().filter(q=>q.module===module.id).length,progress=moduleProgress(module.id),unlocked=unlockedCards().filter(q=>q.module===module.id).length;
  return `<article class="module"><div class="icon" style="background:${module.color}22">${module.icon}</div><h3>${esc(module.title)}</h3><p>${mode==='cards'?`${unlocked} de ${total} flashcards desbloqueadas`:esc(module.short)}</p><div class="meta"><span>${total} preguntas</span><span>${progress}% dominio</span></div><div class="progress"><i style="width:${mode==='cards'?(total?unlocked/total*100:0):progress}%;background:${module.color}"></i></div><button class="open" data-${mode==='cards'?'deck':'module'}="${module.id}" aria-label="${mode==='cards'?'Estudiar':'Abrir'} ${esc(module.title)}"></button></article>`;
}
function bindModuleCards(){$$('[data-module]').forEach(button=>button.onclick=()=>openSetup(button.dataset.module));$$('[data-upload]').forEach(button=>button.onclick=()=>$('#fileInput').click())}

function renderDashboard(){
  const summary=stats(),recent=state.attempts[0],due=dueCards().length;
  $('#dashboard').innerHTML=`<div class="hero"><div class="copy"><span class="tag">✨ APRENDIZAJE CONTINUO</span><h2>${due?`${due} conceptos necesitan repaso`:'Avanza a tu propio ritmo'}</h2><p>${due?'Tu plan combina errores de quiz y memoria de flashcards para decidir qué estudiar hoy.':`Explora ${questions().length} preguntas únicas y desbloquea flashcards conforme estudias.`}</p><button class="primary" data-recommend>${due?'Repasar ahora':'Comenzar quiz'} →</button></div><div class="hero-art">🫀</div></div><div class="stats"><div class="stat"><span class="label">Dominio continuo</span><strong>${learningScore()}%</strong><small>Quiz + memoria</small></div><div class="stat"><span class="label">Precisión</span><strong>${summary.accuracy}%</strong><small>${summary.total} respuestas</small></div><div class="stat"><span class="label">Flashcards</span><strong>${unlockedCards().length}/${questions().length}</strong><small>${due} pendientes</small></div><div class="stat"><span class="label">Sesiones</span><strong>${summary.attempts}</strong><small>${recent?'Última: '+recent.score+' pts':'Sin intentos aún'}</small></div></div><div class="section-head"><div><h2>Tus módulos</h2><p>Completa preguntas para desbloquear sus flashcards</p></div><button class="text-btn" data-all>Ver biblioteca →</button></div><div class="modules">${modules().slice(0,3).map(module=>moduleCard(module)).join('')}</div>`;
  bindModuleCards();$('[data-recommend]').onclick=due?()=>startCards(dueCards()):()=>openSetup('all');$('[data-all]').onclick=renderLibrary;
}
function renderLibrary(){show('library','Biblioteca','Todo tu material');$('#library').innerHTML=`<div class="section-head"><div><h2>Módulos de estudio</h2><p>${modules().length} módulos · ${questions().length} preguntas únicas</p></div></div><div class="modules">${modules().map(module=>moduleCard(module)).join('')}<button class="upload-card" data-upload><div><span style="font-size:35px">＋</span><b>Añadir PDF</b><span>Extracción local · sin subir archivos</span></div></button></div>`;bindModuleCards()}

function openSetup(id){
  session.module=id;session.difficulty='all';session.count=10;session.mode='study';show('setup','Configura tu sesión','Aprende a tu ritmo');
  const module=id==='all'?{title:'Quiz combinado',icon:'⚡',short:'Hasta 40 preguntas únicas de todos los módulos'}:modules().find(item=>item.id===id);
  const focused=questions().filter(q=>id==='all'||q.module===id),counts={all:focused.length,easy:focused.filter(q=>q.difficulty==='easy').length,medium:focused.filter(q=>q.difficulty==='medium').length,hard:focused.filter(q=>q.difficulty==='hard').length,exam:focused.filter(q=>q.difficulty==='exam').length};
  $('#setup').innerHTML=`<div class="setup-grid"><div class="setup-card"><span class="tag">${id==='all'?'TODOS LOS TEMAS':'TEMA SELECCIONADO'}</span><h2>${esc(module.title)}</h2><p>${esc(module.short)}</p><div class="control"><label id="difficultyLabel">Nivel cognitivo</label><div class="segments" id="difficulties" aria-labelledby="difficultyLabel"><button data-v="all" class="selected">Adaptativa<small>${counts.all} · Mixta</small></button><button data-v="easy">Fácil<small>${counts.easy} · Recuerdo</small></button><button data-v="medium">Media<small>${counts.medium} · Aplicación</small></button><button data-v="hard">Difícil<small>${counts.hard} · Análisis</small></button><button data-v="exam">Examen<small>${counts.exam} · Síntesis</small></button></div><p class="filter-note" id="filterNote">La sesión usa exclusivamente el tema elegido, con preguntas distintas y opciones reorganizadas en cada intento.</p></div><div class="control"><label for="count">Número exacto de preguntas</label><div class="count"><input id="count" type="range" min="1" max="40" step="1" value="10"><output aria-live="polite">10</output></div><div class="range-labels"><span>1</span><span>40 máximo</span></div></div><div class="control"><label>Modo</label><div class="mode-options"><button class="mode-option selected" data-mode="study"><b>📖 Estudio</b><small>Sin tiempo, explicación inmediata</small></button><button class="mode-option" data-mode="challenge"><b>⚡ Reto</b><small>Puntos extra por racha</small></button></div></div><button class="secondary wide" id="start">Comenzar sesión →</button></div><div class="panel"><div class="preview-icon">${module.icon}</div><h3>Cómo funciona</h3><ul><li>Entrega exactamente entre 1 y 40 preguntas únicas</li><li>Difícil y Examen usan análisis, secuencias y casos</li><li>Un tema seleccionado nunca se mezcla con otro</li><li>Las opciones cambian de posición en cada intento</li><li>Cada respuesta alimenta el repaso continuo</li></ul></div></div>`;
  $$('#difficulties button').forEach(button=>{button.setAttribute('aria-pressed',String(button.classList.contains('selected')));button.onclick=()=>{$$('#difficulties button').forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false')});button.classList.add('selected');button.setAttribute('aria-pressed','true');session.difficulty=button.dataset.v;$('#filterNote').textContent=button.dataset.v==='all'?'La sesión combina niveles de forma adaptativa, sin repetir preguntas.':`Nivel ${difficultyLabel(button.dataset.v)} activo: ${difficultySkill(button.dataset.v)}. El banco mantiene este nivel hasta completar las preguntas solicitadas.`}});
  $('#count').oninput=event=>{session.count=+event.target.value;event.target.nextElementSibling.value=event.target.value};
  $$('[data-mode]').forEach(button=>{button.setAttribute('aria-pressed',String(button.classList.contains('selected')));button.onclick=()=>{$$('[data-mode]').forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false')});button.classList.add('selected');button.setAttribute('aria-pressed','true');session.mode=button.dataset.mode}});$('#start').onclick=startQuiz;
}
function startQuiz(){
  const available=questions().filter(question=>session.module==='all'||question.module===session.module);if(!available.length){toast('Todavía no hay preguntas disponibles en este tema.');return}
  const requested=Math.max(1,Math.min(40,Number($('#count')?.value)||session.count));session.count=requested;
  const total=Math.min(requested,available.length);if(total<requested)toast(`Este tema contiene ${total} preguntas únicas. No se mezclarán otros temas.`);
  session.questions=buildAdaptiveQuestionSet(available,total,{module:session.module,difficulty:session.difficulty});
  Object.assign(session,{index:0,score:0,streak:0,maxStreak:0,answers:[],answered:false});show('quiz','Sesión en curso',session.mode==='study'?'Modo estudio':'Modo reto');renderQuestion();
}
function renderQuestion(){
  const q=session.questions[session.index],module=modules().find(item=>item.id===q.module),effectiveDifficulty=session.difficulty==='all'?q.difficulty:session.difficulty,level=difficultyLabel(effectiveDifficulty),skill=q.skill||difficultySkill(q.difficulty);session.answered=false;
  $('#quiz').innerHTML=`<div class="quiz-shell"><div class="quiz-top"><button class="ghost" id="quit" aria-label="Salir del quiz">×</button><div class="quiz-progress" role="progressbar" aria-valuemin="1" aria-valuemax="${session.questions.length}" aria-valuenow="${session.index+1}"><i style="width:${(session.index+1)/session.questions.length*100}%"></i></div><span>${session.index+1} / ${session.questions.length}</span></div><div class="score-row" aria-live="polite"><span class="score-chip">⭐ <b id="score">${session.score}</b> puntos</span><span class="score-chip">🔥 <b id="streak">${session.streak}</b> racha</span><span class="score-chip difficulty-chip">${level}</span><span class="score-chip skill-chip">${esc(skill)}</span></div><div class="question-card"><span class="topic">${esc(module?.title||'Módulo personal')} · ${level}</span><h2>${esc(q.text)}</h2><div class="answers">${q.options.map((option,index)=>`<button class="answer" data-answer="${index}" aria-label="Opción ${String.fromCharCode(65+index)}: ${esc(option)}"><b>${String.fromCharCode(65+index)}</b><span>${esc(option)}</span></button>`).join('')}</div><p class="keyboard-hint">Teclas A–D o 1–4 para responder · Enter para continuar</p><div class="explain" id="explain" role="status" aria-live="polite"><span>💡</span><div><strong id="feedbackTitle">Explicación</strong><br>${esc(q.explanation)}</div></div><div class="next-row"><button class="secondary" id="next" hidden>${session.index===session.questions.length-1?'Ver resultados':'Siguiente →'}</button></div></div></div>`;
  $$('[data-answer]').forEach(button=>button.onclick=()=>answerQuestion(+button.dataset.answer));$('#next').onclick=nextQuestion;$('#quit').onclick=()=>{if(confirm('¿Salir de esta sesión? El intento no se guardará.')){renderDashboard();show('dashboard','Hola, estudiante')}};
}
function answerQuestion(selected){
  if(session.answered)return;session.answered=true;const q=session.questions[session.index],correct=selected===q.answer,streak=updateStreak(session.streak,state.streak,correct);session.streak=streak.current;session.maxStreak=Math.max(session.maxStreak,session.streak);state.streak=streak.best;session.score+=correct?(session.mode==='challenge'?100+Math.min(100,session.streak*10):100):0;
  session.answers.push({id:q.id,module:q.module,correct,selected});if(!state.seenQuestions.includes(q.id))state.seenQuestions.push(q.id);
  if(correct){delete state.mistakes[q.id];if(!state.cardProgress[q.id])state.cardProgress[q.id]={...scheduleCard({},'hard'),lastSource:'quiz'}}else{state.mistakes[q.id]=(state.mistakes[q.id]||0)+1;state.cardProgress[q.id]={interval:0,repetitions:0,due:Date.now(),lastRating:'again',lastSource:'quiz'}}
  save();updateChrome();$$('[data-answer]').forEach((button,index)=>{button.disabled=true;if(index===q.answer)button.classList.add('correct');if(index===selected&&!correct)button.classList.add('wrong')});$('#score').textContent=session.score;$('#streak').textContent=session.streak;$('#feedbackTitle').textContent=correct?'Correcto · explicación':'Respuesta correcta · revisa el razonamiento';$('#explain').classList.add('show');$('#next').hidden=false;$('#next').focus();
}
function nextQuestion(){session.index++;session.index<session.questions.length?renderQuestion():finishQuiz()}
function finishQuiz(){
  const correct=session.answers.filter(item=>item.correct).length,total=session.questions.length,percent=Math.round(correct/total*100),byModule={};
  session.answers.forEach(answer=>{byModule[answer.module]??={correct:0,total:0};byModule[answer.module].correct+=answer.correct;byModule[answer.module].total++});
  Object.entries(byModule).forEach(([id,value])=>{state.moduleStats[id]??={correct:0,total:0};state.moduleStats[id].correct+=value.correct;state.moduleStats[id].total+=value.total;const allIds=questions().filter(q=>q.module===id).map(q=>q.id),seenCount=allIds.filter(qid=>state.seenQuestions.includes(qid)).length;if(session.module===id&&seenCount>=Math.min(40,allIds.length)&&!state.completedModules.includes(id))state.completedModules.push(id)});
  state.attempts.unshift({id:Date.now(),date:new Date().toISOString(),module:session.module,mode:session.mode,difficulty:session.difficulty,correct,total,score:session.score,bestStreak:session.maxStreak});state.attempts=state.attempts.slice(0,50);save();updateChrome();show('result','Sesión completada','Tus resultados');
  $('#result').innerHTML=`<div class="result-card"><span class="tag">${percent>=80?'¡EXCELENTE TRABAJO!':percent>=60?'BUEN AVANCE':'SIGUE PRACTICANDO'}</span><h2>${percent>=80?'Ese tema ya late fuerte 💜':'Cada intento te hace avanzar'}</h2><div class="result-ring" style="--pct:${percent}%"><strong>${percent}%</strong></div><p>Acertaste <b>${correct} de ${total}</b>, obtuviste <b>${session.score} puntos</b> y tu mejor racha fue de <b>${session.maxStreak}</b>.</p><div class="result-actions"><button class="secondary" id="again">Intentar de nuevo</button><button class="ghost" id="goCards">Ver flashcards</button><button class="ghost" id="home">Ir al inicio</button></div></div>`;
  $('#again').onclick=startQuiz;$('#goCards').onclick=renderFlashcards;$('#home').onclick=()=>{renderDashboard();show('dashboard','Hola, estudiante')};
}

function renderFlashcards(){
  show('flashcards','Flashcards','Aprendizaje continuo');const unlocked=unlockedCards(),due=dueCards();
  $('#flashcards').innerHTML=`<div class="learning-hero"><div><span class="tag">REPASO INTELIGENTE</span><h2>${unlocked.length?(due.length?`${due.length} tarjetas listas para hoy`:'Repaso diario completado'):'Tus flashcards se desbloquean al estudiar'}</h2><p>Los resultados de quizzes y flashcards comparten el mismo calendario. No existe límite de tarjetas: crecerá con cada módulo que agregues.</p><button class="primary" id="smartReview" ${due.length?'':'disabled'}>${due.length?'Comenzar repaso':unlocked.length?'Vuelve después':'Haz un quiz primero'}</button></div><div class="learning-score"><strong>${learningScore()}%</strong><span>memoria consolidada</span></div></div><div class="section-head"><div><h2>Mazos por tema</h2><p>${unlocked.length} de ${questions().length} tarjetas desbloqueadas</p></div></div><div class="modules">${modules().map(module=>moduleCard(module,'cards')).join('')}</div>`;
  if(due.length)$('#smartReview').onclick=()=>startCards(due);$$('[data-deck]').forEach(button=>button.onclick=()=>{const cards=unlocked.filter(q=>q.module===button.dataset.deck);cards.length?startCards(cards):toast('Responde preguntas de este tema para desbloquear sus flashcards.')});
}
function startCards(cards){cardSession={cards:shuffle(cards),index:0,revealed:false};show('flashcards','Sesión de flashcards','Repetición espaciada');renderCard()}
function renderCard(){
  const q=cardSession.cards[cardSession.index],module=modules().find(item=>item.id===q.module),progress=Math.round(cardSession.index/cardSession.cards.length*100);
  $('#flashcards').innerHTML=`<div class="card-session"><div class="quiz-top"><button class="ghost" id="closeCards">×</button><div class="quiz-progress"><i style="width:${progress}%"></i></div><span>${cardSession.index+1} / ${cardSession.cards.length}</span></div><button class="study-card" id="flipCard" aria-label="Voltear tarjeta"><div class="card-face card-front"><span>${esc(module?.title||'Módulo')}</span><h2>${esc(q.text)}</h2><small>Toca para ver la respuesta</small></div><div class="card-face card-back"><span>RESPUESTA</span><h2>${esc(q.options[q.answer])}</h2><p>${esc(q.explanation)}</p></div></button><div class="rating" id="rating" hidden><p>¿Qué tan bien la recordaste?</p><div><button data-rate="again">Otra vez<small>1 min</small></button><button data-rate="hard">Difícil<small>1 día</small></button><button data-rate="good">Bien<small>3+ días</small></button><button data-rate="easy">Fácil<small>7+ días</small></button></div></div></div>`;
  $('#flipCard').onclick=()=>{cardSession.revealed=!cardSession.revealed;$('#flipCard').classList.toggle('flipped',cardSession.revealed);$('#rating').hidden=!cardSession.revealed};$('#closeCards').onclick=renderFlashcards;$$('[data-rate]').forEach(button=>button.onclick=()=>rateCard(q,button.dataset.rate));
}
function rateCard(q,rating){state.cardProgress[q.id]={...scheduleCard(state.cardProgress[q.id],rating),lastSource:'flashcard'};save();cardSession.index++;updateChrome();if(cardSession.index>=cardSession.cards.length){toast('Repaso completado. Calendario actualizado.');renderFlashcards()}else renderCard()}

function renderMistakes(){show('mistakes','Repaso combinado','Quiz + flashcards');const list=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).map(([id,count])=>({q:questions().find(item=>item.id===id),count})).filter(item=>item.q),due=dueCards();$('#mistakes').innerHTML=list.length||due.length?`<div class="section-head"><div><h2>Plan de refuerzo</h2><p>${list.length} errores de quiz · ${due.length} flashcards pendientes</p></div><button class="secondary" id="reviewAll">Repasar ahora</button></div><div class="list">${list.map(({q,count})=>`<div class="list-item"><span style="font-size:24px">↻</span><div class="grow"><h3>${esc(q.text)}</h3><p>${esc(modules().find(module=>module.id===q.module)?.title||'Módulo personal')}</p></div><span class="pill">${count} ${count===1?'error':'errores'}</span></div>`).join('')}</div>`:`<div class="empty"><span class="big">🎯</span><h2>Todo al día</h2><p>No hay errores ni flashcards pendientes.</p></div>`;if(list.length||due.length)$('#reviewAll').onclick=()=>startCards(due.length?due:list.map(item=>item.q))}
function renderHistory(){show('history','Historial','Tu recorrido de aprendizaje');$('#history').innerHTML=state.attempts.length?`<div class="section-head"><div><h2>Sesiones recientes</h2><p>Se guardan las 50 más recientes</p></div></div><div class="list">${state.attempts.map(attempt=>{const module=attempt.module==='all'?'Quiz combinado':modules().find(item=>item.id===attempt.module)?.title||'Sesión adaptativa';return `<div class="list-item"><span style="font-size:25px">${attempt.correct/attempt.total>=.8?'🏆':'📚'}</span><div class="grow"><h3>${esc(module)}</h3><p>${new Date(attempt.date).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})} · ${attempt.mode==='study'?'Estudio':'Reto'} · ${difficultyLabel(attempt.difficulty)} · 🔥 ${attempt.bestStreak||0}</p></div><span class="pill">${attempt.correct}/${attempt.total}</span><b>${attempt.score} pts</b></div>`}).join('')}</div>`:`<div class="empty"><span class="big">◷</span><h2>Aquí aparecerá tu historial</h2><p>Completa una sesión para comenzar a medir tu avance.</p></div>`}

async function upload(files){for(const file of files){try{toast(`Procesando ${file.name}…`);const pdfjs=await import('./pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='./pdf.worker.mjs';const doc=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,pageTexts=[];for(let pageNumber=1;pageNumber<=Math.min(doc.numPages,80);pageNumber++){const page=await doc.getPage(pageNumber),content=await page.getTextContent();pageTexts.push(reconstructPageText(content.items))}const title=file.name.replace(/\.pdf$/i,''),id='pdf-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),studyStatements=collectStudyStatements(pageTexts),generated=generatePdfQuestions({moduleId:id,title,source:studyStatements,count:60});if(!generated.length){toast(`No se encontró texto suficiente en ${file.name}`);continue}state.customModules.push({id,title,short:`${doc.numPages} páginas · 60 preguntas locales`,icon:'📄',color:'#ff9f43',questions:generated,studyStatements,generatorVersion:3,source:file.name});save();toast(`Módulo añadido: 60 preguntas y flashcards posibles`)}catch(error){console.error(error);toast(`No se pudo leer ${file.name}`)}}renderLibrary()}

$('#fileInput').onchange=event=>upload([...event.target.files]);
document.addEventListener('keydown',event=>{if(!$('#quiz').classList.contains('active')||['INPUT','TEXTAREA'].includes(event.target.tagName))return;const keys={a:0,'1':0,b:1,'2':1,c:2,'3':2,d:3,'4':3};if(!session.answered&&keys[event.key.toLowerCase()]!==undefined){event.preventDefault();$(`[data-answer="${keys[event.key.toLowerCase()]}"]`)?.click()}else if(session.answered&&event.key==='Enter'){event.preventDefault();$('#next')?.click()}});
$$('[data-go]').forEach(button=>button.onclick=()=>{const name=button.dataset.go;if(name==='dashboard'){renderDashboard();show('dashboard','Hola, estudiante')}if(name==='library')renderLibrary();if(name==='flashcards')renderFlashcards();if(name==='mistakes')renderMistakes();if(name==='history')renderHistory()});
updateChrome();renderDashboard();
