export const seedModules=[
 {id:'bio',title:'Modelo biopsicosocial',short:'Equilibrio, riesgo y protección',icon:'🧠',color:'#8b5cf6',source:'Factores biopsicosociales de la salud y la enfermedad.pdf'},
 {id:'signos',title:'Signos, síntomas y lesiones',short:'Conceptos, diferencias y ejemplos',icon:'🩺',color:'#35d3c7',source:'Signos Sintomas Lesiones.pdf'},
 {id:'cardio',title:'Sistema cardiovascular',short:'Corazón, circulación, vasos y sangre',icon:'🫀',color:'#ff647c',source:'Sistema cardiovascular.pdf'}
];
export const seedQuestions=[
['b1','bio','easy','¿Qué propone el modelo biopsicosocial?',['Que solo la genética determina la enfermedad','Que factores biológicos, psicológicos y sociales pueden proteger o aumentar la susceptibilidad','Que el ambiente no influye en la salud','Que toda enfermedad tiene una sola causa'],1,'Integra factores biológicos, psicológicos y sociales, que pueden actuar como protección o riesgo.'],
['b2','bio','easy','Según la presentación, ¿cuándo se logra la salud?',['Cuando no existe estrés','Cuando hay equilibrio entre los factores biológico, psicológico y social','Cuando se elimina el factor social','Cuando el sistema inmune es fuerte'],1,'La presentación resume la salud como un equilibrio entre los tres factores.'],
['b3','bio','easy','¿Cuál es un factor biológico de riesgo mencionado?',['Buenas amistades','Fumar','Autoestima alta','Oportunidad profesional'],1,'Fumar aparece junto con genética, sistema inmune débil y enfermedades previas.'],
['b4','bio','medium','¿Cuál de estos es un factor psicológico de riesgo?',['Burnout','Vacunas','Buena higiene','Sistema inmune fuerte'],0,'El estrés, la falta de autoestima, el burnout y la falta de motivación son riesgos psicológicos.'],
['b5','bio','medium','¿Qué opción es un factor social de protección?',['Presión académica','Malas amistades','Núcleo familiar fuerte','Sobrestimulación ambiental'],2,'Un núcleo familiar fuerte y buenas amistades se presentan como factores sociales protectores.'],
['b6','bio','hard','Andrés tomaba ibuprofeno constantemente. ¿Por qué el caso sugiere ampliar la anamnesis?',['Para ignorar el dolor previo','Para considerar conductas y antecedentes que pueden influir en la enfermedad','Para recetar siempre un medicamento más nuevo','Para descartar cualquier factor social'],1,'El caso introduce la necesidad de recopilar información amplia, coherente con el modelo biopsicosocial.'],
['b7','bio','hard','¿Cuál combinación contiene solo factores de protección mencionados?',['Vacunas, ejercicio y buena autoestima','Burnout, presión laboral y fumar','Sistema inmune débil, estrés y mala higiene','Enfermedades previas, genética y malas amistades'],0,'Vacunas, ejercicio y buena autoestima aparecen expresamente como factores protectores.'],
['b8','bio','exam','¿Qué afirmación refleja mejor el papel del ambiente en el modelo?',['Solo el ambiente macro importa','El ambiente micro y macro puede tener gran importancia en salud y enfermedad','El ambiente sustituye a la biología','El ambiente únicamente protege'],1,'La presentación señala que tanto el ambiente micro como el macro pueden influir de manera importante.'],
['b9','bio','easy','¿Cuál es un factor biológico de protección mencionado?',['Sistema inmune fuerte','Presión laboral','Burnout','Malas amistades'],0,'Un sistema inmune fuerte aparece como factor biológico protector.'],
['b10','bio','medium','¿Cuál de estas condiciones es un factor social de riesgo?',['Buena autoestima','Vacunación','Problemas familiares','Ejercicio'],2,'Los problemas familiares se incluyen entre los factores sociales de riesgo.'],
['b11','bio','hard','¿Qué antecedente del caso de Andrés se repitió antes de la consulta?',['Hematomas','Dolor en el epigastrio','Alucinaciones','Fiebre'],1,'Andrés ya había presentado dolor en el epigastrio tres meses antes y también un año antes.'],
['b12','bio','exam','¿Qué ocurrió después del tratamiento inicial con omeprazol?',['El dolor desapareció','Presentó hematemesis y el dolor no cedió','Dejó de tomar ibuprofeno inmediatamente','Recibió una vacuna'],1,'Una semana después el dolor no cedía y Andrés presentó hematemesis, es decir, vómito con sangre.'],
['s1','signos','easy','¿Qué caracteriza a un signo?',['Es subjetivo','Solo lo percibe el paciente','Es objetivo y cuantificable','Nunca puede medirse'],2,'Un signo es objetivo, cuantificable y puede ser percibido por un tercero.'],
['s2','signos','easy','¿Qué caracteriza a un síntoma?',['Es subjetivo y lo percibe el paciente','Siempre es visible','Es una lesión del tejido','Es necesariamente cuantificable'],0,'Un síntoma es subjetivo, no cuantificable y percibido solamente por el paciente.'],
['s3','signos','easy','¿Cuál es un ejemplo de signo según la presentación?',['Náuseas','Dolor de cabeza','Fiebre','Alucinaciones visuales'],2,'La fiebre aparece como ejemplo de signo.'],
['s4','signos','medium','¿Cuál es un ejemplo de síntoma?',['Hematoma','Eritema','Diarrea','Náuseas'],3,'Las náuseas aparecen entre los ejemplos de síntomas.'],
['s5','signos','medium','¿Qué es una lesión?',['Una percepción subjetiva','Daño a un tejido causado por un agente','Una emoción que afecta la salud','Un parámetro sin relación diagnóstica'],1,'La presentación define lesión como daño a un tejido causado por un agente.'],
['s6','signos','hard','¿Por qué una lesión puede considerarse un signo?',['Porque siempre duele','Porque puede observarse objetivamente por un tercero','Porque solo la percibe el paciente','Porque nunca existe daño tisular'],1,'Al ser un daño observable, puede cumplir con el carácter objetivo de un signo.'],
['s7','signos','hard','¿Qué grupo contiene únicamente lesiones mencionadas?',['Hematoma, eritema y necrosis','Fiebre, vómito y diarrea','Cefalea, náuseas y alucinaciones','Estrés, burnout y dolor'],0,'Hematoma, eritema y necrosis son los ejemplos de lesión de la presentación.'],
['s8','signos','exam','Diferenciar signos y síntomas mejora el diagnóstico porque permite…',['Evitar establecer parámetros','Relacionar parámetros con alguna enfermedad','Usar solo percepciones subjetivas','Descartar las lesiones'],1,'La presentación indica que distinguirlos mejora la precisión al establecer parámetros y relacionarlos con enfermedades.'],
['s9','signos','easy','¿Quién puede percibir un signo además del paciente?',['Solamente el paciente','Un tercero','Nadie','Solo quien presenta dolor'],1,'Un signo puede ser percibido por un tercero porque es objetivo.'],
['s10','signos','medium','¿Cuál opción reúne únicamente ejemplos de signos?',['Fiebre, vómito y diarrea','Náuseas, cefalea y alucinaciones','Hematoma, cefalea y náuseas','Dolor, eritema y estrés'],0,'La presentación muestra fiebre, vómito y diarrea como ejemplos de signos.'],
['s11','signos','hard','Una alucinación visual se clasifica como síntoma porque…',['Siempre causa una lesión','Es subjetiva y la percibe el paciente','Es cuantificable por terceros','Es un daño visible al tejido'],1,'Las alucinaciones visuales aparecen como síntomas, que son subjetivos y percibidos por el paciente.'],
['s12','signos','exam','¿Qué diferencia central existe entre signo y síntoma?',['El signo es objetivo; el síntoma es subjetivo','Ambos son siempre cuantificables','El síntoma siempre implica daño tisular','El signo solo lo percibe el paciente'],0,'La diferencia central presentada es la objetividad y cuantificación del signo frente a la subjetividad del síntoma.'],
['c1','cardio','easy','¿Qué estructuras forman el sistema cardiovascular?',['Corazón, pulmones y nervios','Corazón, vasos sanguíneos y sangre','Riñones, sangre y piel','Vasos, huesos y músculos'],1,'Está formado por corazón, vasos sanguíneos y sangre.'],
['c2','cardio','easy','¿Dónde se localiza el corazón?',['En la cavidad abdominal','En el mediastino de la cavidad torácica','En la cavidad craneal','Detrás del hígado'],1,'La presentación ubica el corazón en el mediastino, dentro de la cavidad torácica.'],
['c3','cardio','easy','¿Cuál es la capa muscular del corazón?',['Endocardio','Pericardio','Miocardio','Epicardio'],2,'El miocardio es la capa muscular formada por miocitos cardiacos.'],
['c4','cardio','medium','¿Qué función tiene el líquido pericárdico?',['Oxigenar la sangre','Lubricar','Formar eritrocitos','Cerrar válvulas'],1,'El saco pericárdico contiene líquido que ayuda a lubricar.'],
['c5','cardio','medium','¿Cuántas cámaras internas tiene el corazón?',['Dos','Tres','Cuatro','Seis'],2,'Tiene dos aurículas y dos ventrículos: cuatro cámaras.'],
['c6','cardio','medium','¿Qué válvula atraviesa la sangre entre aurícula y ventrículo derechos?',['Mitral','Aórtica','Pulmonar','Tricúspide'],3,'En la circulación menor pasa de la aurícula derecha al ventrículo derecho por la tricúspide.'],
['c7','cardio','hard','¿Cuál es el orden correcto al inicio de la circulación mayor?',['Aorta → aurícula izquierda → venas pulmonares','Venas pulmonares → aurícula izquierda → válvula mitral','Venas cavas → aurícula derecha → válvula aórtica','Arteria pulmonar → ventrículo izquierdo → aorta'],1,'La sangre oxigenada llega por venas pulmonares, entra a la aurícula izquierda y atraviesa la mitral.'],
['c8','cardio','hard','¿Dónde ocurre el intercambio gaseoso y de nutrientes?',['En las aurículas','En la red capilar','En las válvulas','En el pericardio'],1,'Los capilares son los vasos más pequeños y allí ocurre el intercambio.'],
['c9','cardio','hard','¿Qué vaso aporta el 80% de la sangre al hígado según la presentación?',['Aorta','Yugular','Vena porta','Seno coronario'],2,'La presentación señala que la vena porta aporta el 80% de la sangre al hígado.'],
['c10','cardio','exam','¿Cuál enunciado sobre los eritrocitos es correcto?',['Tienen núcleo y producen anticuerpos','Son fragmentos para coagulación','Transportan O₂ y CO₂ y carecen de núcleo y mitocondrias','Representan entre 1% y 4% de la sangre'],2,'Los eritrocitos transportan O₂ y CO₂, carecen de núcleo y mitocondrias y se forman en médula ósea.'],
['c11','cardio','exam','¿Qué componente sanguíneo participa en la coagulación?',['Plasma','Plaquetas','Leucocitos','Miocitos'],1,'Las plaquetas son fragmentos celulares que participan en la coagulación.'],
['c12','cardio','exam','¿Cuál comparación entre arterias y venas coincide con la presentación?',['Las venas tienen paredes más resistentes','Las arterias son más profundas y soportan mayor presión','Las arterias siempre transportan CO₂','Las venas siempre transportan O₂'],1,'Las arterias se describen con paredes más elásticas y resistentes, localización profunda y mayor presión.']
,[ 'c13','cardio','easy','¿Qué función principal tiene el corazón?',['Producir leucocitos','Bombear sangre hacia todo el cuerpo','Realizar el intercambio capilar','Almacenar plasma'],1,'El corazón es el órgano muscular encargado de bombear la sangre hacia todo el cuerpo.']
,[ 'c14','cardio','medium','¿Qué capa reviste internamente el corazón y contacta con sus cámaras?',['Epicardio','Miocardio','Endocardio','Pericardio'],2,'El endocardio es el revestimiento interno en contacto con las cámaras cardiacas.']
,[ 'c15','cardio','hard','Después de atravesar la válvula pulmonar, ¿por dónde viaja la sangre?',['Por la aorta','Por la arteria pulmonar hacia los pulmones','Por las venas cavas','Por la vena porta'],1,'En la circulación menor, la sangre atraviesa la válvula pulmonar y viaja por la arteria pulmonar hacia los pulmones.']
,[ 'c16','cardio','exam','¿Qué componente constituye la fracción líquida de la sangre?',['Plaquetas','Plasma','Eritrocitos','Leucocitos'],1,'El plasma es la fracción líquida y contiene proteínas, glucosa y desechos del metabolismo.']
].map(([id,module,difficulty,text,options,answer,explanation])=>({id,module,difficulty,text,options,answer,explanation}));
