import {advancedOverrides} from './advanced-questions.js?v=10';

export const seedModules=[
 {id:'bio',title:'Modelo biopsicosocial',short:'Equilibrio, riesgo y protección',icon:'🧠',color:'#8b5cf6',source:'Factores biopsicosociales de la salud y la enfermedad.pdf'},
 {id:'signos',title:'Signos, síntomas y lesiones',short:'Conceptos, diferencias y ejemplos',icon:'🩺',color:'#35d3c7',source:'Signos Sintomas Lesiones.pdf'},
 {id:'cardio',title:'Sistema cardiovascular',short:'Corazón, circulación, vasos y sangre',icon:'🫀',color:'#ff647c',source:'Sistema cardiovascular.pdf'}
];
const baseQuestions=[
['b1','bio','easy','¿Qué propone el modelo biopsicosocial?',['Que solo la genética determina la enfermedad','Que factores biológicos, psicológicos y sociales pueden proteger o aumentar la susceptibilidad','Que el ambiente no influye en la salud','Que toda enfermedad tiene una sola causa'],1,'Integra factores biológicos, psicológicos y sociales, que pueden actuar como protección o riesgo.'],
['b2','bio','easy','Según la presentación, ¿cuándo se logra la salud?',['Cuando no existe estrés','Cuando hay equilibrio entre los factores biológico, psicológico y social','Cuando se elimina el factor social','Cuando el sistema inmune es fuerte'],1,'La presentación resume la salud como un equilibrio entre los tres factores.'],
['b3','bio','easy','¿Cuál es un factor biológico de riesgo mencionado?',['Buenas amistades','Fumar','Autoestima alta','Oportunidad profesional'],1,'Fumar aparece junto con genética, sistema inmune débil y enfermedades previas.'],
['b4','bio','medium','¿Cuál de estos es un factor psicológico de riesgo?',['Burnout','Vacunas','Buena higiene','Sistema inmune fuerte'],0,'El estrés, la falta de autoestima, el burnout y la falta de motivación son riesgos psicológicos.'],
['b5','bio','medium','¿Qué opción es un factor social de protección?',['Presión académica','Malas amistades','Núcleo familiar fuerte','Sobrestimulación ambiental'],2,'Un núcleo familiar fuerte y buenas amistades se presentan como factores sociales protectores.'],
['b6','bio','hard','Andrés tomaba ibuprofeno constantemente. ¿Por qué el caso sugiere ampliar la anamnesis?',['Para ignorar el dolor previo','Para considerar conductas y antecedentes que pueden influir en la enfermedad','Para recetar siempre un medicamento más nuevo','Para descartar cualquier factor social'],1,'El caso introduce la necesidad de recopilar información amplia, coherente con el modelo biopsicosocial.'],
['b7','bio','hard','¿Cuál combinación contiene solo factores de protección mencionados?',['Vacunas, ejercicio y buena autoestima','Burnout, presión laboral y fumar','Sistema inmune débil, estrés y mala higiene','Enfermedades previas, genética y malas amistades'],0,'Vacunas, ejercicio y buena autoestima aparecen expresamente como factores protectores.'],
['b8','bio','exam','¿Qué afirmación refleja mejor el papel del ambiente en el modelo?',['Solo el ambiente macro importa','El ambiente micro y macro puede tener gran importancia en salud y enfermedad','El ambiente sustituye a la biología','El ambiente únicamente protege'],1,'La presentación señala que tanto el ambiente micro como el macro pueden influir de manera importante.'],
['b9','bio','easy','¿Cuál es un factor biológico de protección mencionado?',['Sistema inmune fuerte','Presión laboral','Burnout','Malas amistades'],0,'Un sistema inmune fuerte aparece como factor biológico protector.'],
['b10','bio','medium','¿Cuál de estas condiciones es un factor social de riesgo?',['Buena autoestima','Vacunación','Problemas familiares','Ejercicio'],2,'Los problemas familiares se incluyen entre los factores sociales de riesgo.'],
['b11','bio','hard','¿Qué antecedente del caso de Andrés se repitió antes de la consulta?',['Hematomas','Dolor en el epigastrio','Alucinaciones','Fiebre'],1,'Andrés ya había presentado dolor en el epigastrio tres meses antes y también un año antes.'],
['b12','bio','exam','¿Qué ocurrió después del tratamiento inicial con omeprazol?',['El dolor desapareció','Presentó hematemesis y el dolor no cedió','Dejó de tomar ibuprofeno inmediatamente','Recibió una vacuna'],1,'Una semana después el dolor no cedía y Andrés presentó hematemesis, es decir, vómito con sangre.'],
['s1','signos','easy','¿Qué caracteriza a un signo?',['Es subjetivo','Solo lo percibe el paciente','Es objetivo y cuantificable','Nunca puede medirse'],2,'Un signo es objetivo, cuantificable y puede ser percibido por un tercero.'],
['s2','signos','easy','¿Qué caracteriza a un síntoma?',['Es subjetivo y lo percibe el paciente','Siempre es visible','Es una lesión del tejido','Es necesariamente cuantificable'],0,'Un síntoma es subjetivo, no cuantificable y percibido solamente por el paciente.'],
['s3','signos','easy','¿Cuál es un ejemplo de signo según la presentación?',['Náuseas','Dolor de cabeza','Fiebre','Alucinaciones visuales'],2,'La fiebre aparece como ejemplo de signo.'],
['s4','signos','medium','¿Cuál es un ejemplo de síntoma?',['Hematoma','Eritema','Diarrea','Náuseas'],3,'Las náuseas aparecen entre los ejemplos de síntomas.'],
['s5','signos','medium','¿Qué es una lesión?',['Una percepción subjetiva','Daño a un tejido causado por un agente','Una emoción que afecta la salud','Un parámetro sin relación diagnóstica'],1,'La presentación define lesión como daño a un tejido causado por un agente.'],
['s6','signos','hard','¿Por qué una lesión puede considerarse un signo?',['Porque siempre duele','Porque puede observarse objetivamente por un tercero','Porque solo la percibe el paciente','Porque nunca existe daño tisular'],1,'Al ser un daño observable, puede cumplir con el carácter objetivo de un signo.'],
['s7','signos','hard','¿Qué grupo contiene únicamente lesiones mencionadas?',['Hematoma, eritema y necrosis','Fiebre, vómito y diarrea','Cefalea, náuseas y alucinaciones','Estrés, burnout y dolor'],0,'Hematoma, eritema y necrosis son los ejemplos de lesión de la presentación.'],
['s8','signos','exam','Diferenciar signos y síntomas mejora el diagnóstico porque permite…',['Evitar establecer parámetros','Relacionar parámetros con alguna enfermedad','Usar solo percepciones subjetivas','Descartar las lesiones'],1,'La presentación indica que distinguirlos mejora la precisión al establecer parámetros y relacionarlos con enfermedades.'],
['s9','signos','easy','¿Quién puede percibir un signo además del paciente?',['Solamente el paciente','Un tercero','Nadie','Solo quien presenta dolor'],1,'Un signo puede ser percibido por un tercero porque es objetivo.'],
['s10','signos','medium','¿Cuál opción reúne únicamente ejemplos de signos?',['Fiebre, vómito y diarrea','Náuseas, cefalea y alucinaciones','Hematoma, cefalea y náuseas','Dolor, eritema y estrés'],0,'La presentación muestra fiebre, vómito y diarrea como ejemplos de signos.'],
['s11','signos','hard','Una alucinación visual se clasifica como síntoma porque…',['Siempre causa una lesión','Es subjetiva y la percibe el paciente','Es cuantificable por terceros','Es un daño visible al tejido'],1,'Las alucinaciones visuales aparecen como síntomas, que son subjetivos y percibidos por el paciente.'],
['s12','signos','exam','¿Qué diferencia central existe entre signo y síntoma?',['El signo es objetivo; el síntoma es subjetivo','Ambos son siempre cuantificables','El síntoma siempre implica daño tisular','El signo solo lo percibe el paciente'],0,'La diferencia central presentada es la objetividad y cuantificación del signo frente a la subjetividad del síntoma.'],
['c1','cardio','easy','¿Qué estructuras forman el sistema cardiovascular?',['Corazón, pulmones y nervios','Corazón, vasos sanguíneos y sangre','Riñones, sangre y piel','Vasos, huesos y músculos'],1,'Está formado por corazón, vasos sanguíneos y sangre.'],
['c2','cardio','easy','¿Dónde se localiza el corazón?',['En la cavidad abdominal','En el mediastino de la cavidad torácica','En la cavidad craneal','Detrás del hígado'],1,'La presentación ubica el corazón en el mediastino, dentro de la cavidad torácica.'],
['c3','cardio','easy','¿Cuál es la capa muscular del corazón?',['Endocardio','Pericardio','Miocardio','Epicardio'],2,'El miocardio es la capa muscular formada por miocitos cardiacos.'],
['c4','cardio','medium','¿Qué función tiene el líquido pericárdico?',['Oxigenar la sangre','Lubricar','Formar eritrocitos','Cerrar válvulas'],1,'El saco pericárdico contiene líquido que ayuda a lubricar.'],
['c5','cardio','medium','¿Cuántas cámaras internas tiene el corazón?',['Dos','Tres','Cuatro','Seis'],2,'Tiene dos aurículas y dos ventrículos: cuatro cámaras.'],
['c6','cardio','medium','¿Qué válvula atraviesa la sangre entre aurícula y ventrículo derechos?',['Mitral','Aórtica','Pulmonar','Tricúspide'],3,'En la circulación menor pasa de la aurícula derecha al ventrículo derecho por la tricúspide.'],
['c7','cardio','hard','¿Cuál es el orden correcto al inicio de la circulación mayor?',['Aorta → aurícula izquierda → venas pulmonares','Venas pulmonares → aurícula izquierda → válvula mitral','Venas cavas → aurícula derecha → válvula aórtica','Arteria pulmonar → ventrículo izquierdo → aorta'],1,'La sangre oxigenada llega por venas pulmonares, entra a la aurícula izquierda y atraviesa la mitral.'],
['c8','cardio','hard','¿Dónde ocurre el intercambio gaseoso y de nutrientes?',['En las aurículas','En la red capilar','En las válvulas','En el pericardio'],1,'Los capilares son los vasos más pequeños y allí ocurre el intercambio.'],
['c9','cardio','hard','¿Qué vaso aporta el 80% de la sangre al hígado según la presentación?',['Aorta','Yugular','Vena porta','Seno coronario'],2,'La presentación señala que la vena porta aporta el 80% de la sangre al hígado.'],
['c10','cardio','exam','¿Cuál enunciado sobre los eritrocitos es correcto?',['Tienen núcleo y producen anticuerpos','Son fragmentos para coagulación','Transportan O₂ y CO₂ y carecen de núcleo y mitocondrias','Representan entre 1% y 4% de la sangre'],2,'Los eritrocitos transportan O₂ y CO₂, carecen de núcleo y mitocondrias y se forman en médula ósea.'],
['c11','cardio','exam','¿Qué componente sanguíneo participa en la coagulación?',['Plasma','Plaquetas','Leucocitos','Miocitos'],1,'Las plaquetas son fragmentos celulares que participan en la coagulación.'],
['c12','cardio','exam','¿Cuál comparación entre arterias y venas coincide con la presentación?',['Las venas tienen paredes más resistentes','Las arterias son más profundas y soportan mayor presión','Las arterias siempre transportan CO₂','Las venas siempre transportan O₂'],1,'Las arterias se describen con paredes más elásticas y resistentes, localización profunda y mayor presión.']
,[ 'c13','cardio','easy','¿Qué función principal tiene el corazón?',['Producir leucocitos','Bombear sangre hacia todo el cuerpo','Realizar el intercambio capilar','Almacenar plasma'],1,'El corazón es el órgano muscular encargado de bombear la sangre hacia todo el cuerpo.']
,[ 'c14','cardio','medium','¿Qué capa reviste internamente el corazón y contacta con sus cámaras?',['Epicardio','Miocardio','Endocardio','Pericardio'],2,'El endocardio es el revestimiento interno en contacto con las cámaras cardiacas.']
,[ 'c15','cardio','hard','Después de atravesar la válvula pulmonar, ¿por dónde viaja la sangre?',['Por la aorta','Por la arteria pulmonar hacia los pulmones','Por las venas cavas','Por la vena porta'],1,'En la circulación menor, la sangre atraviesa la válvula pulmonar y viaja por la arteria pulmonar hacia los pulmones.']
,[ 'c16','cardio','exam','¿Qué componente constituye la fracción líquida de la sangre?',['Plaquetas','Plasma','Eritrocitos','Leucocitos'],1,'El plasma es la fracción líquida y contiene proteínas, glucosa y desechos del metabolismo.']
].map(([id,module,difficulty,text,options,answer,explanation])=>({id,module,difficulty,text,options,answer,explanation}));

const supplementalBio=[
['b13','bio','easy','¿Cuánto tiempo llevaba Andrés con dolor de epigastrio al llegar a consulta?',['Tres días','Tres semanas','Cinco días','Un año'],0,'El caso indica que Andrés presentaba dolor en el epigastrio desde hacía tres días.'],
['b14','bio','easy','¿Qué medicamento tomaba Andrés de forma constante?',['Omeprazol','Pantoprazol','Ibuprofeno','Ninguno'],2,'Andrés señaló que tomaba ibuprofeno constantemente por una lesión en la espalda.'],
['b15','bio','easy','¿Cuál fue el diagnóstico inicial de Andrés?',['Gastritis','Alcoholismo','Necrosis','Hipertensión'],0,'El diagnóstico final de la primera consulta fue gastritis.'],
['b16','bio','easy','¿Qué significa hematemesis?',['Dolor de cabeza','Vómito con sangre','Diarrea con sangre','Dolor de espalda'],1,'La presentación aclara que hematemesis significa vómito con sangre.'],
['b17','bio','easy','¿Cuál es un factor social de protección?',['Buenas amistades','Burnout','Fumar','Sistema inmune débil'],0,'Las buenas amistades aparecen entre los factores sociales protectores.'],
['b18','bio','easy','¿Cuál es un factor psicológico de protección?',['Presión académica','Buena autoestima','Falta de motivación','Estrés'],1,'La buena autoestima se presenta como un factor psicológico protector.'],
['b19','bio','medium','¿Qué dosis inicial de omeprazol recibió Andrés?',['20 mg cada 24 horas por 5 días','40 mg cada 8 horas','20 mg una sola vez','5 mg por 20 días'],0,'El tratamiento indicado fue omeprazol de 20 mg cada 24 horas durante cinco días.'],
['b20','bio','medium','¿Qué tratamiento recibió Andrés en la segunda visita?',['Ibuprofeno 20 mg','Pantoprazol 20 mg cada 24 horas por 7 días','Vacunas por 5 días','Omeprazol durante un mes'],1,'El médico cambió el tratamiento a pantoprazol de 20 mg cada 24 horas por siete días.'],
['b21','bio','medium','¿Qué factor de riesgo corresponde al entorno académico?',['Presión académica','Buena alimentación','Ejercicio','Vacunación'],0,'La presión laboral o académica se menciona como factor social de riesgo.'],
['b22','bio','medium','¿Cuál de estos hábitos protege frente a la enfermedad?',['Fumar','Falta de higiene','Hacer ejercicio','Sobrestimulación ambiental'],2,'El ejercicio aparece entre las condiciones protectoras.'],
['b23','bio','medium','¿Qué característica familiar actúa como protección?',['Problemas familiares','Núcleo familiar fuerte','Presión laboral','Malas amistades'],1,'Un núcleo familiar fuerte es un factor social protector.'],
['b24','bio','medium','¿Cuál situación aumenta la susceptibilidad a enfermar?',['Buena higiene','Sistema inmune fuerte','Enfermedades previas','Oportunidad profesional'],2,'Las enfermedades previas se incluyen como factor biológico de riesgo.'],
['b25','bio','medium','¿Qué aspecto psicológico puede elevar el riesgo de enfermedad?',['Falta de motivación','Buena autoestima','Buenas amistades','Vacunación'],0,'La falta de motivación aparece entre los factores psicológicos de riesgo.'],
['b26','bio','hard','¿Qué información del caso muestra recurrencia del problema?',['El dolor había aparecido tres meses antes y un año antes','Andrés nunca había sentido dolor','Solo presentó fiebre una vez','El dolor comenzó después del pantoprazol'],0,'Andrés relató episodios previos de dolor tres meses antes y un año antes.'],
['b27','bio','hard','¿Por qué “medicamento más nuevo” no basta para asegurar un mejor resultado?',['Porque debe considerarse información integral del paciente','Porque nunca se usan medicamentos','Porque elimina los factores sociales','Porque todo dolor desaparece solo'],0,'El caso destaca que cambiar a un medicamento nuevo sin ampliar la información no resolvió el problema.'],
['b28','bio','hard','¿Qué dimensión incluye pensamientos y emociones?',['Biológica','Psicológica','Anatómica','Hematológica'],1,'Las pautas de pensamiento y las emociones corresponden a la dimensión psicológica.'],
['b29','bio','hard','¿Qué dimensiones del ambiente reconoce el modelo?',['Solo el ambiente hospitalario','Ambiente micro y macro','Solo el ambiente familiar','Ninguna dimensión ambiental'],1,'La presentación reconoce la influencia tanto del ambiente micro como del macro.'],
['b30','bio','hard','¿Cuál combinación reúne dos riesgos sociales?',['Problemas familiares y malas amistades','Vacunas y ejercicio','Buena autoestima y motivación','Sistema inmune fuerte y alimentación'],0,'Los problemas familiares y las malas amistades figuran entre los riesgos sociales.'],
['b31','bio','hard','¿Cuál combinación reúne dos protecciones biológicas o conductuales?',['Vacunas y buena alimentación','Burnout y estrés','Presión académica y fumar','Malas amistades y falta de higiene'],0,'Vacunas y buena alimentación aparecen como factores protectores.'],
['b32','bio','hard','Si una persona tiene estrés y burnout, ¿qué dimensión concentra esos riesgos?',['Psicológica','Biológica','Cardiovascular','Anatómica'],0,'Estrés y burnout son ejemplos psicológicos de riesgo.'],
['b33','bio','exam','¿Qué pregunta ampliaría mejor la anamnesis de Andrés desde el enfoque biopsicosocial?',['¿Qué otros medicamentos, hábitos, estrés y antecedentes tienes?','¿Quieres el medicamento más nuevo?','¿Prefieres no hablar de tu entorno?','¿Podemos ignorar episodios anteriores?'],0,'El modelo requiere explorar información biológica, psicológica y social relevante.'],
['b34','bio','exam','¿Qué conclusión apoya la persistencia de síntomas tras dos tratamientos?',['La recopilación de información debe ser más amplia','Siempre debe aumentarse la dosis','El ambiente nunca importa','La hematemesis no es relevante'],0,'La persistencia refuerza la necesidad de una evaluación integral antes de decidir el tratamiento.'],
['b35','bio','exam','Una persona vacunada, activa y con buena alimentación reúne principalmente…',['Factores de protección','Factores de riesgo psicológico','Lesiones','Signos subjetivos'],0,'Vacunas, ejercicio y buena alimentación son factores de protección.'],
['b36','bio','exam','Una persona con sistema inmune débil y enfermedades previas reúne…',['Factores biológicos de riesgo','Factores sociales protectores','Síntomas subjetivos','Factores psicológicos protectores'],0,'Ambos elementos aparecen como riesgos de tipo biológico.'],
['b37','bio','exam','¿Qué diferencia esencial existe entre riesgo y protección?',['El riesgo aumenta la probabilidad de enfermar y la protección la reduce','Ambos siempre causan enfermedad','La protección aumenta la susceptibilidad','El riesgo solo es genético'],0,'Los factores de riesgo elevan la exposición o susceptibilidad; los protectores la disminuyen.'],
['b38','bio','exam','¿Qué ejemplo muestra interacción de dimensiones biopsicosociales?',['Genética, estrés y presión laboral en una misma persona','Solo una válvula cardiaca','Únicamente una medición de fiebre','Un tejido sin contexto'],0,'El modelo integra simultáneamente elementos biológicos, psicológicos y sociales.'],
['b39','bio','exam','¿Cuál intervención aborda más de una dimensión protectora?',['Ejercicio, buenas amistades y autoestima','Fumar y presión laboral','Aislamiento y burnout','Mala higiene y estrés'],0,'La opción reúne protección biológica o conductual, social y psicológica.'],
['b40','bio','exam','Según el modelo, ¿una misma dimensión puede contener riesgo y protección?',['Sí, depende de la condición o conducta','No, cada dimensión solo protege','Solo la dimensión social','Solo después de una lesión'],0,'Cada dimensión incluye elementos que pueden proteger o aumentar la susceptibilidad.']
];

const supplementalSigns=[
['s13','signos','easy','¿Un signo es objetivo o subjetivo?',['Objetivo','Subjetivo','Imaginario','Siempre emocional'],0,'La presentación define el signo como objetivo.'],
['s14','signos','easy','¿Un síntoma es cuantificable?',['Sí, siempre','No, se presenta como no cuantificable','Solo por terceros','Únicamente con laboratorio'],1,'El síntoma se describe como no cuantificable.'],
['s15','signos','easy','¿Cuál ejemplo corresponde a una lesión?',['Hematoma','Náusea','Dolor de cabeza','Alucinación visual'],0,'El hematoma aparece como ejemplo de lesión.'],
['s16','signos','easy','¿Cuál ejemplo corresponde a un síntoma?',['Eritema','Necrosis','Dolor de cabeza','Fiebre'],2,'El dolor de cabeza aparece como ejemplo de síntoma.'],
['s17','signos','easy','¿Cuál ejemplo corresponde a un signo?',['Vómito','Náusea','Alucinación','Dolor de cabeza'],0,'El vómito se presenta como ejemplo de signo.'],
['s18','signos','easy','¿Qué estructura sufre daño en una lesión?',['Un tejido','Una emoción','Una amistad','Una válvula siempre'],0,'Una lesión es daño a un tejido causado por un agente.'],
['s19','signos','medium','¿Por quién es percibido solamente un síntoma?',['Por el paciente','Por cualquier tercero','Solo por un laboratorio','Por nadie'],0,'El síntoma es percibido solamente por el paciente.'],
['s20','signos','medium','¿Qué rasgo permite medir un signo?',['Su carácter cuantificable','Su subjetividad','Que solo lo siente el paciente','La ausencia de parámetros'],0,'Los signos son cuantificables.'],
['s21','signos','medium','¿Qué opción no es un ejemplo de lesión de la presentación?',['Necrosis','Eritema','Hematoma','Náusea'],3,'La náusea es un síntoma; las otras tres opciones son lesiones.'],
['s22','signos','medium','¿Qué opción no es un ejemplo de síntoma?',['Dolor de cabeza','Náuseas','Alucinaciones visuales','Diarrea'],3,'La diarrea aparece como signo, no como síntoma.'],
['s23','signos','medium','¿Qué opción no es un ejemplo de signo?',['Fiebre','Vómito','Diarrea','Alucinación visual'],3,'La alucinación visual se incluye como síntoma.'],
['s24','signos','medium','¿Qué origina una lesión según la definición?',['Un agente que daña tejido','Solo una emoción','La percepción de un tercero','La falta de medición'],0,'La lesión es daño tisular causado por un agente.'],
['s25','signos','medium','¿Qué característica comparten fiebre, vómito y diarrea en la presentación?',['Son signos','Son síntomas','Son factores sociales','Son capas cardiacas'],0,'Los tres aparecen como ejemplos de signos.'],
['s26','signos','hard','Un profesional mide la temperatura elevada de un paciente. ¿Cómo se clasifica?',['Como signo','Como síntoma','Como factor psicológico','Como anamnesis'],0,'Al ser objetiva y cuantificable, la fiebre se clasifica como signo.'],
['s27','signos','hard','El paciente refiere náusea sin que un tercero pueda medirla directamente. ¿Qué es?',['Síntoma','Signo','Lesión obligatoria','Factor protector'],0,'La náusea es subjetiva y aparece como ejemplo de síntoma.'],
['s28','signos','hard','Se observa un área de eritema en la piel. ¿Cómo puede clasificarse?',['Lesión y posible signo','Solo síntoma','Factor social','Emoción'],0,'El eritema es una lesión y una lesión puede considerarse signo.'],
['s29','signos','hard','¿Por qué el dolor de cabeza no se clasifica como signo en la presentación?',['Porque es subjetivo y lo percibe el paciente','Porque siempre se mide','Porque daña tejido necesariamente','Porque es visible a terceros'],0,'El dolor de cabeza aparece como síntoma subjetivo.'],
['s30','signos','hard','¿Qué relación existe entre lesión y signo?',['Una lesión puede considerarse signo','Todo signo es necesariamente lesión','Nunca se relacionan','Una lesión siempre es síntoma'],0,'La presentación señala expresamente que una lesión puede ser considerada signo.'],
['s31','signos','hard','¿Qué dato aporta mayor objetividad al diagnóstico?',['Un parámetro cuantificable','Una percepción no comunicada','Una emoción aislada','Una suposición sin observación'],0,'Los parámetros objetivos y cuantificables mejoran la precisión diagnóstica.'],
['s32','signos','hard','¿Cuál pareja contrasta correctamente signo y síntoma?',['Fiebre y náusea','Náusea y fiebre como dos signos','Hematoma y eritema como síntomas','Cefalea y alucinación como signos'],0,'La fiebre es signo y la náusea es síntoma.'],
['s33','signos','exam','Un paciente describe alucinaciones visuales. ¿Qué propiedad determina su clasificación?',['La percepción subjetiva del paciente','La medición por terceros','El daño visible de tejido','La coagulación'],0,'Las alucinaciones visuales son síntomas por su carácter subjetivo.'],
['s34','signos','exam','¿Cuál secuencia favorece la precisión diagnóstica?',['Identificar, diferenciar, establecer parámetros y relacionar con enfermedad','Ignorar signos y usar suposiciones','Considerar todo como síntoma','Evitar parámetros cuantificables'],0,'La presentación relaciona la diferenciación con parámetros y enfermedades para mejorar la precisión.'],
['s35','signos','exam','Un hematoma observado por el médico cumple principalmente con…',['Daño tisular observable','Percepción exclusiva del paciente','Ausencia de agente','Subjetividad no cuantificable'],0,'El hematoma es una lesión observable y puede considerarse signo.'],
['s36','signos','exam','¿Cuál conjunto contiene dos síntomas y una lesión?',['Náusea, cefalea y necrosis','Fiebre, vómito y diarrea','Hematoma, eritema y necrosis','Diarrea, fiebre y náusea'],0,'Náusea y cefalea son síntomas; necrosis es lesión.'],
['s37','signos','exam','¿Cuál conjunto contiene dos signos y un síntoma?',['Fiebre, vómito y náusea','Cefalea, náusea y alucinación','Hematoma, eritema y necrosis','Dolor, estrés y fiebre'],0,'Fiebre y vómito son signos; náusea es síntoma.'],
['s38','signos','exam','¿Qué error reduce la precisión diagnóstica?',['Confundir una percepción subjetiva con un parámetro objetivo','Medir un signo','Relacionar parámetros con enfermedad','Distinguir lesiones'],0,'Confundir categorías impide establecer parámetros diagnósticos adecuados.'],
['s39','signos','exam','¿Qué afirmación integra correctamente los tres conceptos?',['Un signo es objetivo, un síntoma subjetivo y una lesión es daño tisular','Los tres son siempre subjetivos','Toda lesión solo la percibe el paciente','Ningún signo es cuantificable'],0,'Resume las definiciones centrales de signo, síntoma y lesión.'],
['s40','signos','exam','¿Por qué es clínicamente útil conocer estas diferencias?',['Porque mejora la precisión al relacionar parámetros con enfermedad','Porque elimina la anamnesis','Porque vuelve subjetivos todos los datos','Porque impide observar lesiones'],0,'Ese es el propósito indicado al final de la presentación.']
];

const supplementalCardio=[
['c17','cardio','easy','¿Qué transporta el sistema cardiovascular hasta las células?',['Oxígeno y nutrientes','Solo hormonas','Únicamente agua','Impulsos nerviosos'],0,'El sistema transporta oxígeno y nutrientes hasta todas las células.'],
['c18','cardio','easy','¿Hacia qué lado apunta el ápice del corazón?',['Izquierda','Derecha','Arriba','Atrás'],0,'La localización se describe como central con el ápice hacia la izquierda.'],
['c19','cardio','easy','¿Entre qué espacios intercostales se localiza el corazón?',['Del tercero al quinto','Del primero al segundo','Del sexto al octavo','Solo en el décimo'],0,'La presentación lo ubica específicamente entre el tercer y quinto espacio intercostal.'],
['c20','cardio','easy','¿Cuál es la capa externa del corazón?',['Epicardio','Endocardio','Miocardio','Plasma'],0,'El epicardio es la capa externa del corazón.'],
['c21','cardio','easy','¿Qué saco aloja al corazón?',['Pericardio','Endocardio','Capilar','Aorta'],0,'El pericardio es el saco que aloja al corazón.'],
['c22','cardio','easy','¿Cuántas aurículas tiene el corazón?',['Dos','Una','Tres','Cuatro'],0,'Las cuatro cámaras incluyen dos aurículas y dos ventrículos.'],
['c23','cardio','medium','¿Cuántas válvulas auriculoventriculares hay?',['Dos','Cuatro','Una','Ninguna'],0,'El corazón tiene dos válvulas auriculoventriculares.'],
['c24','cardio','medium','¿Cuántas válvulas semilunares hay?',['Dos','Tres','Cuatro','Una'],0,'El corazón tiene dos válvulas semilunares.'],
['c25','cardio','medium','¿Qué otro nombre recibe la circulación menor?',['Pulmonar','General','Coronaria','Portal'],0,'La circulación menor también se conoce como pulmonar.'],
['c26','cardio','medium','¿Qué otro nombre recibe la circulación mayor?',['General','Pulmonar','Capilar','Menor'],0,'La circulación mayor también se conoce como general.'],
['c27','cardio','medium','¿Qué sangre llega por las venas cavas?',['No oxigenada desde el cuerpo','Oxigenada desde pulmones','Solo plasma','Sangre del hígado únicamente'],0,'Las venas cavas llevan sangre no oxigenada del cuerpo a la aurícula derecha.'],
['c28','cardio','medium','¿Qué cámara recibe sangre de las venas pulmonares?',['Aurícula izquierda','Aurícula derecha','Ventrículo derecho','Aorta'],0,'La sangre oxigenada de las venas pulmonares entra a la aurícula izquierda.'],
['c29','cardio','hard','¿Qué válvula comunica aurícula y ventrículo izquierdos?',['Mitral o bicúspide','Tricúspide','Pulmonar','Aórtica'],0,'La sangre atraviesa la válvula mitral o bicúspide para llegar al ventrículo izquierdo.'],
['c30','cardio','hard','¿Qué válvula atraviesa la sangre antes de entrar a la aorta?',['Aórtica','Pulmonar','Tricúspide','Mitral'],0,'Desde el ventrículo izquierdo atraviesa la válvula aórtica.'],
['c31','cardio','hard','¿Qué arterias llevan sangre a la cabeza?',['Carótidas','Radiales','Coronarias','Cavas'],0,'Las carótidas llevan sangre a la cabeza.'],
['c32','cardio','hard','¿Qué arterias irrigan el corazón?',['Coronarias','Yugulares','Radiales','Pulmonares solamente'],0,'Las arterias coronarias irrigan al corazón.'],
['c33','cardio','hard','¿En qué arteria se menciona la toma de pulso?',['Radial','Aorta','Carótida únicamente','Porta'],0,'La arteria radial irriga el brazo y se usa para tomar el pulso.'],
['c34','cardio','hard','¿Qué venas recogen sangre no oxigenada de la cabeza?',['Yugulares','Cavas exclusivamente','Coronarias','Radiales'],0,'Las yugulares recogen sangre no oxigenada de la cabeza.'],
['c35','cardio','exam','¿Qué estructura recoge sangre no oxigenada del corazón?',['Seno coronario','Vena porta','Aorta','Carótida'],0,'El seno coronario recoge la sangre no oxigenada del corazón.'],
['c36','cardio','exam','¿Qué células sanguíneas cumplen funciones de defensa?',['Leucocitos','Eritrocitos','Plaquetas','Miocitos'],0,'Los leucocitos son células de defensa.'],
['c37','cardio','exam','¿Qué porcentaje promedio representan los eritrocitos?',['45%','1%','4%','80%'],0,'Los eritrocitos representan en promedio 45% del total de la sangre.'],
['c38','cardio','exam','¿Qué proporción representan los leucocitos?',['Entre 1% y 4%','45%','80%','Más de 90%'],0,'Los leucocitos representan del 1% al 4%.'],
['c39','cardio','exam','¿Dónde se forman los eritrocitos?',['En la médula ósea','En el pericardio','En la aorta','En los capilares'],0,'La presentación indica que los eritrocitos se forman en la médula ósea.'],
['c40','cardio','exam','¿Qué sustancias contiene el plasma según la presentación?',['Proteínas, glucosa y desechos metabólicos','Solo oxígeno','Únicamente plaquetas','Miocitos y válvulas'],0,'El plasma contiene proteínas, glucosa y desechos del metabolismo.']
];

const mapQuestion=([id,module,difficulty,text,options,answer,explanation])=>({id,module,difficulty,text,options,answer,explanation});
const rawQuestions=[...baseQuestions,...supplementalBio.map(mapQuestion),...supplementalSigns.map(mapQuestion),...supplementalCardio.map(mapQuestion)];
const upgradedQuestions=rawQuestions.map(question=>advancedOverrides[question.id]?{...question,...advancedOverrides[question.id]}:question);

function synthesisQuestions(moduleId){
 const source=upgradedQuestions.filter(question=>question.module===moduleId&&['hard','exam'].includes(question.difficulty));
 return source.map((first,index)=>{
  const second=source[(index+7)%source.length],firstCorrect=first.options[first.answer],secondCorrect=second.options[second.answer],firstWrong=first.options[(first.answer+1)%first.options.length],secondWrong=second.options[(second.answer+1)%second.options.length];
  return{id:`${moduleId}-synthesis-${index+1}`,module:moduleId,difficulty:index<10?'hard':'exam',skill:index<10?'Análisis doble':'Síntesis de examen',text:`Reto integrado ${index+1}. Resuelve simultáneamente ambos planteamientos:\nI) ${first.text}\nII) ${second.text}`,options:[`I: ${firstCorrect} · II: ${secondCorrect}`,`I: ${firstWrong} · II: ${secondCorrect}`,`I: ${firstCorrect} · II: ${secondWrong}`,`I: ${firstWrong} · II: ${secondWrong}`],answer:0,explanation:`Planteamiento I: ${first.explanation} Planteamiento II: ${second.explanation}`};
 });
}

export const seedQuestions=[...upgradedQuestions,...seedModules.flatMap(module=>synthesisQuestions(module.id))];
