import assert from 'node:assert/strict';import {seedModules,seedQuestions} from './data.js';
import {buildAdaptiveQuestionSet,buildQuestionSet,scheduleCard,updateStreak} from './quiz-engine.js';
import {generatePdfQuestions,upgradeCustomModule} from './pdf-question-generator.js';
assert.equal(seedModules.length,3);assert.equal(seedQuestions.length,120);for(const q of seedQuestions){assert.ok(seedModules.some(m=>m.id===q.module),q.id);assert.equal(q.options.length,4,q.id);assert.ok(q.answer>=0&&q.answer<4,q.id);assert.ok(q.explanation.length>15,q.id)}
const ids=seedQuestions.map(q=>q.id);assert.equal(new Set(ids).size,ids.length);console.log(`✓ ${seedQuestions.length} preguntas validadas en ${seedModules.length} módulos`);
for(const module of seedModules){const modulePool=seedQuestions.filter(q=>q.module===module.id);assert.equal(modulePool.length,40,module.id);const set=buildQuestionSet(modulePool,40,()=>.42);assert.equal(set.length,40);assert.equal(new Set(set.map(q=>q.id)).size,40);assert.ok(set.every(q=>q.module===module.id))}for(const difficulty of ['easy','medium','hard','exam']){const pool=seedQuestions.filter(q=>q.difficulty===difficulty);const set=buildQuestionSet(pool,40,()=>.42);assert.equal(set.length,Math.min(40,pool.length));assert.equal(new Set(set.map(q=>q.id)).size,set.length);assert.ok(set.every(q=>q.difficulty===difficulty),difficulty)}
assert.equal(buildQuestionSet(seedQuestions.slice(0,7),20,()=>.42).length,7);console.log('✓ Hasta 40 preguntas únicas por sesión, sin repetir y respetando la dificultad');
const focused=buildAdaptiveQuestionSet(seedQuestions,40,{module:'signos',difficulty:'hard'},()=>.42);assert.equal(focused.length,40);assert.equal(new Set(focused.map(q=>q.id)).size,40);assert.ok(focused.slice(0,10).every(q=>q.difficulty==='hard'));assert.ok(focused.slice(0,3).every(q=>q.module==='signos'));assert.equal(buildAdaptiveQuestionSet([...seedQuestions,seedQuestions[0]],99).length,40);console.log('✓ Tema y dificultad se priorizan sin reducir el máximo ni introducir duplicados');
const now=1700000000000;assert.equal(scheduleCard({},'again',now).due,now+60000);assert.equal(scheduleCard({},'good',now).interval,3);assert.equal(scheduleCard({interval:7,repetitions:2},'easy',now).interval,21);console.log('✓ El calendario de repetición espaciada ajusta cada próximo repaso');
const generated=generatePdfQuestions({moduleId:'pdf-test',title:'Archivo breve',source:['La salud integra factores biológicos, psicológicos y sociales que se relacionan entre sí.'],count:40,random:()=>.25});assert.equal(generated.length,40);assert.equal(new Set(generated.map(q=>q.id)).size,40);assert.equal(new Set(generated.map(q=>q.text)).size,40);assert.ok(generated.every(q=>q.options.length===4&&q.answer>=0));const upgraded=upgradeCustomModule({id:'old',title:'Anterior',questions:generated.slice(0,9)});assert.equal(upgraded.questions.length,40);console.log('✓ Incluso un PDF corto permite solicitar 20 o 40 preguntas distintas');
let streak={current:0,best:0};for(const correct of [true,true,true,false,true,true,false])streak=updateStreak(streak.current,streak.best,correct);assert.deepEqual(streak,{current:0,best:3});assert.deepEqual(updateStreak(2,5,true),{current:3,best:5});console.log('✓ La racha actual se reinicia al fallar y la mejor racha se conserva');
